name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Adjust to your desired Terraform version

    - name: Configure AWS credentials
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
        aws configure set aws_access_key_id $(cat aws_access_key_id)
        aws configure set aws_secret_access_key $(cat aws_secret_access_key)
        aws configure set default.region ${{ secrets.AWS_REGION }}
        
    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform Configuration
      run: terraform validate

    - name: Plan Terraform Changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve tfplan

    # You can add more steps as needed for your workflow.
